# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlineBanChan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnlineBanChan
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'RxBlocking'

end

target 'OnlineBanChanTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'RxBlocking'
end
